sf.cmd project retrieve start --manifest package0.xml --target-org WSProd
sf.cmd project retrieve start --manifest package1.xml --target-org WSProd
sf.cmd project retrieve start --manifest package2.xml --target-org WSProd
sf.cmd project retrieve start --manifest package3.xml --target-org WSProd
sf.cmd project retrieve start --manifest package4.xml --target-org WSProd
sf.cmd project retrieve start --manifest package5.xml --target-org WSProd
sf.cmd project retrieve start --manifest package6.xml --target-org WSProd
sf.cmd project retrieve start --manifest package7.xml --target-org WSProd
sf.cmd project retrieve start --manifest package8.xml --target-org WSProd
sf.cmd project retrieve start --manifest package9.xml --target-org WSProd
sf.cmd project retrieve start --manifest package10.xml --target-org WSProd
sf.cmd project retrieve start --manifest package11.xml --target-org WSProd
sf.cmd project retrieve start --manifest package12.xml --target-org WSProd
sf.cmd project retrieve start --manifest package13.xml --target-org WSProd
sf.cmd project retrieve start --manifest package14.xml --target-org WSProd
sf.cmd project retrieve start --manifest package15.xml --target-org WSProd
sf.cmd project retrieve start --manifest package16.xml --target-org WSProd
sf.cmd project retrieve start --manifest package17.xml --target-org WSProd
sf.cmd project retrieve start --manifest package18.xml --target-org WSProd
sf.cmd project retrieve start --manifest package19.xml --target-org WSProd
sf.cmd project retrieve start --manifest package20.xml --target-org WSProd
sf.cmd project retrieve start --manifest package21.xml --target-org WSProd
sf.cmd project retrieve start --manifest package22.xml --target-org WSProd
sf.cmd project retrieve start --manifest package23.xml --target-org WSProd
sf.cmd project retrieve start --manifest package24.xml --target-org WSProd
sf.cmd project retrieve start --manifest package25.xml --target-org WSProd
sf.cmd project retrieve start --manifest package26.xml --target-org WSProd
sf.cmd project retrieve start --manifest package27.xml --target-org WSProd
sf.cmd project retrieve start --manifest package28.xml --target-org WSProd
sf.cmd project retrieve start --manifest package29.xml --target-org WSProd
sf.cmd project retrieve start --manifest package30.xml --target-org WSProd
sf.cmd project retrieve start --manifest package31.xml --target-org WSProd
sf.cmd project retrieve start --manifest package32.xml --target-org WSProd
sf.cmd project retrieve start --manifest package33.xml --target-org WSProd
sf.cmd project retrieve start --manifest package34.xml --target-org WSProd
sf.cmd project retrieve start --manifest package35.xml --target-org WSProd
sf.cmd project retrieve start --manifest package36.xml --target-org WSProd
sf.cmd project retrieve start --manifest package37.xml --target-org WSProd
sf.cmd project retrieve start --manifest package38.xml --target-org WSProd
sf.cmd project retrieve start --manifest package39.xml --target-org WSProd
sf.cmd project retrieve start --manifest package40.xml --target-org WSProd
sf.cmd project retrieve start --manifest package41.xml --target-org WSProd
sf.cmd project retrieve start --manifest package42.xml --target-org WSProd
sf.cmd project retrieve start --manifest package43.xml --target-org WSProd
sf.cmd project retrieve start --manifest package44.xml --target-org WSProd
sf.cmd project retrieve start --manifest package45.xml --target-org WSProd
sf.cmd project retrieve start --manifest package46.xml --target-org WSProd
sf.cmd project retrieve start --manifest package47.xml --target-org WSProd
sf.cmd project retrieve start --manifest package48.xml --target-org WSProd
sf.cmd project retrieve start --manifest package49.xml --target-org WSProd
sf.cmd project retrieve start --manifest package50.xml --target-org WSProd
sf.cmd project retrieve start --manifest package51.xml --target-org WSProd
sf.cmd project retrieve start --manifest package52.xml --target-org WSProd
sf.cmd project retrieve start --manifest package53.xml --target-org WSProd
sf.cmd project retrieve start --manifest package54.xml --target-org WSProd
sf.cmd project retrieve start --manifest package55.xml --target-org WSProd
sf.cmd project retrieve start --manifest package56.xml --target-org WSProd
sf.cmd project retrieve start --manifest package57.xml --target-org WSProd
sf.cmd project retrieve start --manifest package58.xml --target-org WSProd
sf.cmd project retrieve start --manifest package59.xml --target-org WSProd
sf.cmd project retrieve start --manifest package60.xml --target-org WSProd
sf.cmd project retrieve start --manifest package61.xml --target-org WSProd
sf.cmd project retrieve start --manifest package62.xml --target-org WSProd
sf.cmd project retrieve start --manifest package63.xml --target-org WSProd
sf.cmd project retrieve start --manifest package64.xml --target-org WSProd
sf.cmd project retrieve start --manifest package65.xml --target-org WSProd
sf.cmd project retrieve start --manifest package66.xml --target-org WSProd
sf.cmd project retrieve start --manifest package67.xml --target-org WSProd
sf.cmd project retrieve start --manifest package68.xml --target-org WSProd
sf.cmd project retrieve start --manifest package69.xml --target-org WSProd
sf.cmd project retrieve start --manifest package70.xml --target-org WSProd
sf.cmd project retrieve start --manifest package71.xml --target-org WSProd
sf.cmd project retrieve start --manifest package72.xml --target-org WSProd
sf.cmd project retrieve start --manifest package73.xml --target-org WSProd
sf.cmd project retrieve start --manifest package74.xml --target-org WSProd
sf.cmd project retrieve start --manifest package75.xml --target-org WSProd
sf.cmd project retrieve start --manifest package76.xml --target-org WSProd
sf.cmd project retrieve start --manifest package77.xml --target-org WSProd
sf.cmd project retrieve start --manifest package78.xml --target-org WSProd
sf.cmd project retrieve start --manifest package79.xml --target-org WSProd
sf.cmd project retrieve start --manifest package80.xml --target-org WSProd
sf.cmd project retrieve start --manifest package81.xml --target-org WSProd
sf.cmd project retrieve start --manifest package82.xml --target-org WSProd
sf.cmd project retrieve start --manifest package83.xml --target-org WSProd
sf.cmd project retrieve start --manifest package84.xml --target-org WSProd
sf.cmd project retrieve start --manifest package85.xml --target-org WSProd
sf.cmd project retrieve start --manifest package86.xml --target-org WSProd
sf.cmd project retrieve start --manifest package87.xml --target-org WSProd
sf.cmd project retrieve start --manifest package88.xml --target-org WSProd
sf.cmd project retrieve start --manifest package89.xml --target-org WSProd
sf.cmd project retrieve start --manifest package90.xml --target-org WSProd
sf.cmd project retrieve start --manifest package91.xml --target-org WSProd
sf.cmd project retrieve start --manifest package92.xml --target-org WSProd
sf.cmd project retrieve start --manifest package93.xml --target-org WSProd
sf.cmd project retrieve start --manifest package94.xml --target-org WSProd
sf.cmd project retrieve start --manifest package95.xml --target-org WSProd
sf.cmd project retrieve start --manifest package96.xml --target-org WSProd
sf.cmd project retrieve start --manifest package97.xml --target-org WSProd
sf.cmd project retrieve start --manifest package98.xml --target-org WSProd
