@isTest
public class NCMT_TestRALPOEClass {

	static testmethod void OfficeRAProject1() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff1','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', false,'','',true,'');
        
	}
	/*
	static testmethod void OfficeRAProject2() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff123','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Roofing','Roofing - 2017 - 367',false,'Replace');
        
	}
	
 	static testmethod void OfficeRAProject2() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff2','Office','Virginia','State Average','Core/Shell with TI'
                                        ,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Roofing','Roofing - 2017 - 74',false,'Repair');
        
    }
    
	static testmethod void OfficeRAProject20() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff123','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Roofing','Roofing - 2017 - 71',false,'Repair');
        
	}
	
	static testmethod void OfficeRAProject200() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff3','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Roofing','Roofing - 2017 - 315',false,'Replace');
        
	}
	   
	static testmethod void OfficeRAProject21() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff4','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Plumbing','Plumbing - 2017 - 651',false,'Replace');
        
	}

	static testmethod void OfficeRAProject210() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff5','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Plumbing','Plumbing - 2017 - 664',false,'Replace');
        
	}

	static testmethod void OfficeRAProject211() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff6','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Plumbing','Plumbing - 2017 - 668',false,'Replace');
        
	}

	static testmethod void OfficeRAProject212() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff7','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Plumbing','Plumbing - 2017 - 680',false,'Replace');
        
	}
		
	static testmethod void OfficeRAProject22() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff8','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Exterior Closure','Exterior closure - 2017 - 681',false,'Replace');
        
	}

	static testmethod void OfficeRAProject221() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff9','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Exterior Closure','Exterior Closure - 2017 - 117',false,'Repair');
        
	}
	
	static testmethod void OfficeRAProject23() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff10','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Land Improvements','Land Improvements - 2017 - 187',false,'Replace');
        
	}

	static testmethod void OfficeRAProject231() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff11','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Land Improvements','Land Improvements - 2017 - 246',false,'Replace');
        
	}

	static testmethod void OfficeRAProject232() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff12','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', true,'Land Improvements','Land Improvements - 2017 - 54',false,'Repair');
        
	}*/

	static testmethod void OfficeRAProject3() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff13','Courthouse','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', false, false, true, 'New Fit Out', false,'','',true,'');
        
	}
		
	static testmethod void OfficeRAProject4() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff14','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', false, false, true, 'Refresh', false,'','',false,'');
        
	}
	
	static testmethod void OfficeRAProject5() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff15','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', false, false, true, 'Renovate', false,'','',false,'');
        
	}

	static testmethod void OfficeRAProject6() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Parametric Entry', 'testProjCodeCovRAOff16','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', false, false, true, 'New Fit Out', false,'','',false,'');
        
	}
	
	/*static testmethod void OfficeRAProject66() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff17','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', true, false, false, 'Refresh', false,'Roofing','Roofing - 2017 - 71',false,'Repair');
        
	}*/
	   
	static testmethod void OfficeRAProject7() {
        NCMT_TestRALPOEDataClass.CreateRAProject('Repair & Alteration - Work Item Detail', 'testProjCodeCovRAOff17','Office','Virginia','State Average','Core/Shell with TI'
        								,'Single Story','P100: Baseline','Level II - Low','Urban', false, false, true, 'Refresh', false,'','',false,'');
        
	}	

	static testmethod void LPOEProject() {
        NCMT_TestRALPOEDataClass.CreateLPOEProject('New Construction', 'testProjCodeCovLPOE1','LPOE','California','State Average','Core/Shell only'
        								,'Single Story','P100: Baseline','Level II - Low','Urban','Medium','Medium', true);
        
	}
	
	static testmethod void LPOEProject2() {
        NCMT_TestRALPOEDataClass.CreateLPOEProject('New Construction', 'testProjCodeCovLPOE2','LPOE','California','State Average','Core/Shell only'
        								,'Single Story','P100: Baseline','Level II - Low','Remote','Small','Small', false);
        
	}	

}