@isTest
public class TestPBS_gBUILD_MpcICController
{
    public static testMethod void testPlaceholder()
    {  
        system.assert(true);  
    }  
    
/*  
public static testMethod void testMPCIC()
  {  
        PBS_gBUILD_MpcInstructionsCController con= new PBS_gBUILD_MpcInstructionsCController ();
        String sample = null;
        con.mpcNum=10;
        con.projType='PM';
         //string s=
        //con.instructions='test';
    sample = con.instructions;
    system.debug(sample);
   system.assert(sample!=null);
    con.projType='CM';
     sample = con.instructions;
     con.mpcNum=10000;
     sample = con.instructions;
      system.debug(sample);
      system.assertEquals(sample ,'No instructions for MPC 10,000');
        }
*/ 
}