public with sharing class TriggerValue {
   public static boolean firstRun = True;
    public static boolean isinsert = false;  
    public static boolean isupdate = true;
    public static boolean isupdate1 = true;
    public static boolean isInsertPT= false; 
    public static boolean isFirstRun= true;
    public static boolean isClone = false;
    public static boolean isMinCost = false;
    public static boolean isMinCostCurrent = false;
    public static boolean isPerformanceUpdate = false;
    public static boolean isCostUpdate = false;
    public static boolean isHPLosUpdate = false;
    public static boolean isTCOPLPUpdate = false;
    public static boolean isPaste = false;
}